title: VARG

encoding: utf-8

plugins_dir: "_plugins"

strict_front_matter: true

safe: true

exclude:
  [
    .idea,
    README.md,
    .liquidrc,
    css,
    Gemfile,
    Gemfile.lock,
    Markdown_cheatsheet.pdf,
  ]
